name: Release (Ayam-Semesta)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.sbp_a212af997b1d47871aae2e0431ffb872577e7539 }}
      SUPABASE_DB_PASSWORD: ${{ secrets.ayamSemesta.08 }}
      SUPABASE_PROJECT_ID: ${{ secrets.qidnvwyagidmnlafsaer }}

    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $qidnvwyagidmnlafsaer
      - run: supabase db push

  apply:
    runs-on: ubuntu-latest
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.sbp_a212af997b1d47871aae2e0431ffb872577e7539 }}
      TF_VAR_linked_project: ${{ secrets.qidnvwyagidmnlafsaer }}
    defaults:
      run:
        working-directory: supabase/remotes

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - run: terraform init
      - run: terraform apply -auto-approve -no-color